FROM alexeiled/docker-oracle-xe-11g

RUN sed -i 's/33817b96c0aa/abc/g' /u01/app/oracle/product/11.2.0/xe/network/admin/tnsnames.ora
RUN sed -i 's/33817b96c0aa/abc/g' /u01/app/oracle/product/11.2.0/xe/network/admin/listener.ora

ENV LD_LIBRARY_PATH /usr/local/lib
ENV ORACLE_HOME /u01/app/oracle/product/11.2.0/xe

CMD ["/u01/app/oracle/product/11.2.0/xe/bin/lsnrctl","start"]

COPY start2.sh start2.sh
#CMD chmod +x start2.sh

COPY start3.sh start3.sh
RUN chmod +x start3.sh

CMD /start.sh
